Serilog:
  Using: [ "Serilog.Sinks.Console" ]
  MinimumLevel:
    Default: "Information"
    Override:
      SS14.Jetfish: "Debug"

Server:
  RequiredClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"

ConnectionStrings:
  default: "Server=127.0.0.1;Port=5432;Database=jetfish;User Id=postgres;Password=postgres;Include Error Detail=true;"

CircuitOptions:
  DetailedErrors: true

Files:
  GifToVideoConversion: true
  MinimumGifVideoDimensions: 64x64
